name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # This job runs on the self-hosted runner
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Docker Stack
        run: |
          echo "Deploying on self-hosted runner..."
          docker compose up -d --remove-orphans